### ISSUE TITLE
Add a config adjustment for Untamed Wilds?

### ISSUE THREAD

**Issue by Cixon** [MarkusBordihn/adaptive_performance_tweaks#10]
Link: https://www.curseforge.com/minecraft/mc-mods/untamedwilds/

**Comment by MarkusBordihn** [comment]
I prepared thr mod support, but unfortunately this project has an experimental flag.
Which means it will not synchronize across the CurseForge network and I will wait until it's leave this "experimental" state to release the mod support.

**Comment by Cixon** [comment]
Understandable. Thank you!

**Comment by Cixon** [comment]
@MarkusBordihn latest update for untamed wilds released the experimental tag! check it out:
https://www.curseforge.com/minecraft/mc-mods/untamedwilds/

**Comment by MarkusBordihn** [comment]
Sorry, forgot to provide an update on this. It's implemented and available over the config file since some weeks.
Please open a new issue entry in the case there are any issues or so.
