### ISSUE TITLE
Mobs and Entities Disappearing - adaptive_performance_tweaks_1.16.5-0.4.4.jar

### ISSUE THREAD

**Issue by Reshy** [MarkusBordihn/adaptive_performance_tweaks#12]
Mobs and Entities Disappearing
After a while on a Multiplayer server there seems to be an issue where players cannot see entities anymore, or at least intermittently has this issue.

Reproduce:
Seems to happen over time on my LAN server, might be lag related.  Either way entities will start having an issue where your view gets desynced from where APT thinks you're viewing, leading to entities not rendering.

Expected behavior
Mobs should only be un-rendered when they're not in front of the player.  

Screenshots
![djz3ex3](https://user-images.githubusercontent.com/2096384/118385624-6dc8e800-b5c5-11eb-853f-9db6c154f1d6.png)

Mod List:

    Just Enough Resources (JER) (by way2muchnoise)
    Create (by simibubi)
    Hwyla (by TehNut)
    Polymorph (Forge) (by TheIllusiveC4)
    Macaw's Roofs (by sketch_macaw)
    In Control! (by McJty)
    Cosmetic Armor Reworked (by LainMI)
    Collective (by Serilum)
    Absent by Design (by Lothrazar)
    Botania (by Vazkii)
    The Abyss: Chapter II (by y4z0n)
    Project: Vibrant Journeys (by solis_nova123)
    FTB Library (Forge) (by FTB)
    Enhanced Celestials - Blood Moons & Harvest Moons (by Corgi_Taco)
    Fast Furnace minus Replacement (by tfarecnim)
    Frozen Up (by ninnih_)
    Quark O' Plenty (by rosy162)
    Kiwi 🥝 (by Snownee_)
    CoFH Core (by TeamCoFH)
    ATO - All the Ores (by ATMTeam)
    Fruit Trees 🍊 (by Snownee_)
    Druidcraft (by VulpTheHorseDog)
    Abnormals Core (by TeamAbnormals)
    Repurposed Structures (Forge) (by telepathicgrunt)
    Waystones (by BlayTheNinth)
    CleanCut (by Rongmario)
    Extended Caves (by Polyvalord)
    Placebo (by Shadows_of_Fire)
    Subterranean Wilderness (by Melonslise)
    Reliquary v1.3 (by P3pp3rF1y)
    Trample Stopper (by UnRealDinnerbone)
    Bookshelf (by DarkhaxDev)
    Infernal Expansion (by InfernalStudios)
    Curios Quark Oddities Backpack (by 6LeoMC)
    Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)
    Water Strainer (by Ruuubi)
    Stack Refill (by Serilum)
    Savage & Ravage (by TeamAbnormals)
    AI Improvements (by QueenOfMissiles)
    The Endergetic Expansion (by TeamAbnormals)
    Spartan Weaponry (by ObliviousSpartan)
    Client Tweaks (by BlayTheNinth)
    YUNG's API (Forge) (by YUNGNICKYOUNG)
    V-Tweaks (by oitsjustjose)
    Autumnity (by TeamAbnormals)
    Ice and Fire: Dragons (by alex1the1666)
    Adaptive Performance Tweaks (APTweaks) (by Kaworru)
    Stone Circles (by Julek2006Domino)
    Armor Toughness Bar (by tfarecnim)
    Curious Elytra (Forge) (by TheIllusiveC4)
    Chocolate Fix (by AlcatrazEscapee)
    Large Ore Deposits (by EnderLanky)
    Spice of Life: Carrot Edition (by lordcazsius)
    Botany Pots (by DarkhaxDev)
    Curios API (Forge) (by TheIllusiveC4)
    Wawla - What Are We Looking At (by DarkhaxDev)
    Dungeon Crawl (by XIROC1337)
    Recast (by Serilum)
    CraftTweaker (by Jaredlll08)
    When Dungeons Arise (by Aureljz)
    Oh The Biomes You'll Go (by AOCAWOL)
    YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
    Macaw's Bridges (by sketch_macaw)
    Archer's Paradox (by TeamCoFH)
    Quark (by Vazkii)
    AutoRegLib (by Vazkii)
    Quark Oddities (by Vazkii)
    Macaw's Furniture (by sketch_macaw)
    Nourished Nether (by MuffinsDev)
    Architectury API (Forge) (by shedaniel)
    Xaero's World Map (by xaero96)
    Botany Trees (by DarkhaxDev)
    AmbientSounds 3 (by CreativeMD)
    Biomes O' Plenty (by Forstride)
    FallingTree (Forge&Fabric) (by RakSrinaNa)
    Blood Magic (by WayofTime)
    ForgeEndertech (by EnderLanky)
    Cyclic (by Lothrazar)
    AttributeFix (by DarkhaxDev)
    Atmospheric (by TeamAbnormals)
    FerriteCore (Forge) (by malte0811)
    Terraqueous (by ShetiPhian)
    Mod Name Tooltip (by mezz)
    Builders Crafts & Additions (Forge) (by MRHminer)
    Flower Seeds (by Trhod177)
    AppleSkin (by squeek502)
    Fast Leaf Decay (by olafskiii)
    Smooth Boot (Forge) (by UltimateBoomer)
    The Twilight Forest (by Benimatic)
    Just Enough Items (JEI) (by mezz)
    FastWorkbench Minus Replacement (by tfarecnim)
    Chunk-Pregenerator (by Speiger)
    The Outer End (by BlueDuckYT)
    Mowzie's Mobs (by bobmowzie)
    Traverse Reforged (by Noobanidus)
    Overloaded Armor Bar (by tfarecnim)
    Caelus API (Forge) (by TheIllusiveC4)
    Towers Of The Wild (by idrae_)
    ReAuth (by TechnicianLP)
    Default Options (by BlayTheNinth)
    Patchouli (by Vazkii)
    Charm Reforged (by svenhjol)
    RandomPatches (Forge) (by TheRandomLabs)
    YUNG's Extras (Forge) (by YUNGNICKYOUNG)
    Aquaculture 2 (by Shadowclaimer)
    Ores Above Diamonds (by Squidsword)
    Login Shield (by Glasspelican)
    Artifacts (by ochotonida)
    Save My Stronghold! (Forge) (by YUNGNICKYOUNG)
    ShetiPhianCore (by ShetiPhian)
    Mystical Agriculture (by BlakeBr0)
    Macaw's Trapdoors (by sketch_macaw)
    Inventory Pets (by Purplicious_Cow_)
    Block Swap (by Corgi_Taco)
    Supplementaries (by MehVahdJukaar)
    Neapolitan (by TeamAbnormals)
    Spartan Shields (by ObliviousSpartan)
    Valhelsia Structures (by ValhelsiaTeam)
    CreativeCore (by CreativeMD)
    Toast Control (by Shadows_of_Fire)
    Psi (by Vazkii)
    Upgrade Aquatic (by TeamAbnormals)
    Clumps (by Jaredlll08)
    Curio of Undying (Forge) (by TheIllusiveC4)
    BountifulBaubles (by Cursed1nferno)
    Enhanced Mushrooms (Forge) (by team_aurora_modding)
    Xaero's Minimap (by xaero96)
    Cucumber Library (by BlakeBr0)
    Citadel (by alex1the1666)
    TrashSlot (by BlayTheNinth)
    Get It Together, Drops! (by bl4ckscor3)
    Mystical World (by EpicSquid315)
    JEITweaker (by Jaredlll08)
    Enchanted Golden Apple Crafting (by betathunder1)
    BetterEnd (Forge) (by Beethoven92)
    Spiders 2.0 (by TheCyberBrick)
    Sound Filters (by Tmtravlr)
    Better Animals Plus (by cybercat5555)
    [Add-On] The Abyss: Beginning (by y4z0n)
    Friendly Fire (by DarkhaxDev)

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report. Could you please let me know if pressing `F3 + A` is making the entities appearing again?

The mod is not adjusting the "render" part of Minecraft and only adjusting the view-distance settings.
At the moment it's sound like a specific issue with the LAN server.
Let me know what happen with pressing `F3 + A` and I will additionally try to reproduce the issue on my side.
