### ISSUE TITLE
Entity Error

### ISSUE THREAD

**Issue by kxazd** [MarkusBordihn/adaptive_performance_tweaks#16]
Error with the mod abyssal depths
26.05 23:08:24 [Server] Server thread/WARN [APTweaks/]: Unknown entity name for entity BodyPartEntity['Sailfish'/816347, l='ServerLevel[world]', x=5558.50, y=56.00, z=5102.69] in minecraft:overworld. Please report this issue under https://github.com/MarkusBordihn/adaptive_performance_tweaks/issues/]!

**Comment by MarkusBordihn** [comment]
Thanks for the report, seems the AbyssalDepths mod use some outdated definitions like "net.minecraft.entity.MultiPartEntityPart", e.g.: https://github.com/Chumbanotz/AbyssalDepths/blob/master/src/main/java/chumbanotz/abyssaldepths/entity/BodyPart.java

I implemented a fix with 1.0.2 to ignore this type of former implementations.
