### ISSUE TITLE
Fishing with modified rods; APT doesn't recognize bobber

### ISSUE THREAD

**Issue by alfalfascout** [MarkusBordihn/adaptive_performance_tweaks#18]
**Describe the bug**
One of my server members was fishing with an enchanted rod and adaptive performance tweaks doesn't know what to do with the bobber. Fishing seems to work but I get this message in the console a lot:
`[APTweaks/]: Unknown entity name for entity FishingBobberEntity['Fishing Bobber'/32631004, l='ServerLevel[world]', x=-1329.45, y=64.71, z=-104.62] (entity.minecraft.fishing_bobber) in minecraft:overworld. Please report this issue under https://github.com/MarkusBordihn/adaptive_performance_tweaks/issues/`
Edit: My server member reports that they sometimes are not getting anything from fishing, even when the bobber bobs, which could be lag or could be related to this.

**To Reproduce**
I'm not sure what the steps are, but I can give you a screenshot of the rod my server member was fishing with.

**Expected behavior**
Adaptive Performance Tweaks doesn't post message to the console about how confusing a fishing bobber is.

**Screenshots**
This is the fishing rod information on hover.
![image](https://user-images.githubusercontent.com/9934097/119923980-c5aa0c00-bf40-11eb-9d69-63d0e8da5d08.png)

**Debugging**
I have a log file but I'm afraid to post it publicly because it's like 17MB and it happened on a server with lots of people I can't be sure consent to having their stuff on the open internet? Is there an email I can send it to or something?

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
Here's a zip of the manifest and html modlist of the server, let me know if you need the client too.
[Skydragon SERVER 1.16.5-0.9.zip](https://github.com/MarkusBordihn/adaptive_performance_tweaks/files/6557922/Skydragon.SERVER.1.16.5-0.9.zip)

**Additional context**
The fishing rod was enchanted, named, and seemed to have NBT tags from elemental craft.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the detailed report, the issue should be fixed in version 1.0.4 and higher for this item and all similar items.
