### ISSUE TITLE
Creepers lighting on fire for split second

### ISSUE THREAD

**Issue by jakey1995abc** [MarkusBordihn/adaptive_performance_tweaks#2]
**Describe the bug**
During night time, all creepers light (flash) on fire for 1 frame every few seconds or so (only tested when connecting to paper server)

**To Reproduce**
1. join server with mod
2. wait until night for creepers to spawn
3. See flashing creeper display

**Expected behavior**
Creepers to not flash on fire randomly

**Screenshots**
Imagine seeing a creeper set on fire, but for a split second and to all creepers in sight...

**Debugging**
Before reporting a issue please use `/aptweaks debug true` to enable debugging and check if there is anything relevant in the debug.log file.

**Additional context**

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report, this is an experimental feature which should burn creepers during daylight.
