### ISSUE TITLE
Farlanders Mod Support

### ISSUE THREAD

**Issue by blacksythe** [MarkusBordihn/adaptive_performance_tweaks#25]
**Is your feature request related to a problem? Please describe.**
Farlanders mod, seems to overpower other spawns with this mod enabled

**Describe the solution you'd like**
Enable Support for the Farlanders mod

**Describe alternatives you've considered**
Adding them to a clear mobs list, but they would only respawn

**Additional context**
No

**Comment by MarkusBordihn** [comment]
Mod: https://www.curseforge.com/minecraft/mc-mods/farlanders
