### ISSUE TITLE
[1.16.5] Add spawn support for Twist

### ISSUE THREAD

**Issue by Cixon** [MarkusBordihn/adaptive_performance_tweaks#27]
**Mod link:** https://www.curseforge.com/minecraft/mc-mods/twist

### **Entities IDs**
twist:boomba
twist:buckus
twist:charger
twist:ghoul
twist:groundedslug
twist:howl
twist:peblings
twist:purglin
twist:slug
twist:sporel

**Comment by MarkusBordihn** [comment]
I added the mod support for Twist.
Unfortunately the documentation is not the best and the source code is not available, so I was not really able to correct categorize all mobs.

Feel free to submit a change request for https://github.com/MarkusBordihn/adaptive_performance_tweaks/blob/main/src/main/java/de/markusbordihn/adaptiveperformancetweaks/config/mods/TwistConfig.java if the categorization needs adjustments.
