### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by NomSTee** [MarkusBordihn/adaptive_performance_tweaks#3]
https://0bin.net/paste/s3N9gwiT#XlPaTpSsULiuaPkVAfdztGhwJ2uw7SB999VmFpRxq-C

Crashed while i was in nether exploring, now upon joining will automatically crash server

**Comment by MarkusBordihn** [comment]
Thanks for the report. Was not really able to reproduce the issue even with crashing the test sever several time.
But I added some additional checks to avoid this exception to crash the server.
I'm currently testing the new version on my server, if this runs fine for the next 1 hour I will put it live.

**Comment by MarkusBordihn** [comment]
Please reopen this issue if you are able to reproduce it with the latest version 0.3.8 on your side. Thanks.
