### ISSUE TITLE
Gamerules adjusted even when disabled.

### ISSUE THREAD

**Issue by Tatara88** [MarkusBordihn/adaptive_performance_tweaks#7]
If player login optimization is on then every login decreases randomTickSpeed and maxEntityCramming as there is no check to make sure that gameruleOptimization is enabled for the login  event

https://github.com/MarkusBordihn/adaptive_performance_tweaks/blob/3dd6ebcab7800edb72b003841089427b84994715/src/main/java/de/markusbordihn/adaptiveperformancetweaks/player/PlayerOptimization.java#L55

**Comment by Tatara88** [comment]
Also i think the lower limit for maxEntityCramming should be around 3-5 as once it gets to 1 any entity that touches another entity will take damage. Killed a Wandering trader by him walking up to me.

**Comment by jarquafelmu** [comment]
I'm having the cramming issue kill off my minecolony villages just from them walking through each other

**Comment by MarkusBordihn** [comment]
Thanks for the note. I added a safty check which give a warning when using a lower value and minecolony to avoid this.
The default minEntityCramming is now 5 and could be adjusted over the config, if needed.

**Comment by jarquafelmu** [comment]
thank you!

**Comment by nanonestor** [comment]
Good that cramming was made configurable and bumped by default - however nobody is ever going to want their Minecolonies colonists deleted under any circumstance. Colonies can have 150+ colonist entities and at certain times they can almost all be grouped because of all going to bed travelling narrow passages, group summon commands, etc. Can they be set to get ignored - or add a config option for this? Thanks.

**Comment by Tatara88** [comment]
The cramming means you have to have more than 5 villagers on the same block
at the same time

**Comment by nanonestor** [comment]
Yes that's what I'm saying lol. It's actually fairly common the way Minecolonies does some things now and then.

**Comment by MarkusBordihn** [comment]
Unfortunately EntityCramming is a Minecraft core feature, so I'm not able to exclude specific entities.
For the spawn control all entities with a custom name are ignored which includes minecolonies villagers.
The last version includes a minEntityCramming setting which could be set to 20, but I will add a additional "enable/disable" switch in the next version. The default Minecraft EntityCramming value was 24 or so.
